### ISSUE TITLE
Error: unknow location

### ISSUE THREAD

**Issue by IppolitoGermer** [enziop/mixamo_converter#38]
hi, i have this error

Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\mixamo_converter-master\__init__.py", line 369, in execute
    quaternion_clean_post=mixamo.quaternion_clean_post)
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\mixamo_converter-master\mixamoconv.py", line 453, in batch_hip_to_root
    file_loader[file_ext](file.path)
  File "C:\Users|AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\mixamo_converter-master\mixamoconv.py", line 425, in <lambda>
    use_prepost_rot=True),
  File "A:\Blender\2.78\scripts\modules\bpy\ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "A:\Blender\2.78\scripts\addons\io_scene_fbx\__init__.py", line 234, in execute
    return import_fbx.load(self, context, **keywords)
  File "A:\Blender\2.78\scripts\addons\io_scene_fbx\import_fbx.py", line 2843, in load
    _(); del _
  File "A:\Blender\2.78\scripts\addons\io_scene_fbx\import_fbx.py", line 2841, in _
    blen_read_animations(fbx_tmpl_astack, fbx_tmpl_alayer, stacks, scene, settings.anim_offset)
  File "A:\Blender\2.78\scripts\addons\io_scene_fbx\import_fbx.py", line 676, in blen_read_animations
    if id_data.type == 'MESH' and id_data.parent and id_data.parent.type == 'ARMATURE':
AttributeError: 'NoneType' object has no attribute 'type'

location: A:\Blender\2.78\scripts\modules\bpy\ops.py:189

location: <unknown location>:-1

**Comment by IppolitoGermer** [comment]
fix: disable "ignore leaf bones"
