### ISSUE TITLE
Crash when converting an Anim in 2.8

### ISSUE THREAD

**Issue by Rob-bb** [enziop/mixamo_converter#49]
[Idle.zip](https://github.com/enziop/mixamo_converter/files/3588985/Idle.zip)

When importing a anim (attached) I get this error in he 2.8 branch

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mixamo_converter\__init__.py", line 366, in execute
    quaternion_clean_post=mixamo.quaternion_clean_post)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mixamo_converter\mixamoconv.py", line 496, in batch_hip_to_root
    bonenames=bpy.context.scene.mixamo.knee_bones.decode('utf-8').split(','))
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mixamo_converter\mixamoconv.py", line 166, in apply_kneefix
    armature.data.edit_bones[name].select_tail = True
KeyError: 'bpy_prop_collection[key]: key "calf_r" not found'

location: <unknown location>:-1

```

**Comment by Rob-bb** [comment]
I think this was something I did wrong, and not a bug, but maybe it could have some error trapping added.  Please close this if you think it is not relevant.
