### ISSUE TITLE
Unable to function

### ISSUE THREAD

**Issue by GodFather-GH** [enziop/mixamo_converter#90]
bpy.ops.object.select_all(action='SELECT')

bpy.ops.object.delete(use_global=False)

Python: Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\mixamo_converter-master\__init__.py", line 352, in execute
    numfiles = mixamoconv.batch_hip_to_root(
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\mixamo_converter-master\mixamoconv.py", line 490, in batch_hip_to_root
    file_loader[file_ext](file)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\mixamo_converter-master\mixamoconv.py", line 443, in <lambda>
    ".fbx": lambda filename: bpy.ops.import_scene.fbx(
  File "X:\3D\Blender\blender-3.0.1-windows-x64\blender-3.0.1-windows-x64\3.0\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: 错误: Version 6100 unsupported, must be 7100 or later

location: <unknown location>:-1

**Comment by GodFather-GH** [comment]
Blender The log information

**Comment by enziop** [comment]
It seems you try to convert FBX files that were saved with an old FBX version you need to use at least 7.1 (FBX 2011) or later as the blender importer doesn't support older versions like e.g.: 6.1

**Comment by GodFather-GH** [comment]
> 

Thanks
