### ISSUE TITLE
Dont know if project is kept up with or not but: RuntimeError: Operator bpy.ops.object.select_all.poll() failed, context is incorrect

### ISSUE THREAD

**Issue by iamuRon** [enziop/mixamo_converter#92]
Python: Traceback (most recent call last):
  File "C:\Users\ragan\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\mixamo_converter-master\__init__.py", line 352, in execute
    numfiles = mixamoconv.batch_hip_to_root(
  File "C:\Users\ragan\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\mixamo_converter-master\mixamoconv.py", line 478, in batch_hip_to_root
    bpy.ops.object.select_all(action='SELECT')
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.select_all.poll() failed, context is incorrect

location: <unknown location>:-1

**Comment by iamuRon** [comment]
Fixed it, somehow Deleting the original folders for input/output and making new ones seemed to solve it.

**Comment by iamuRon** [comment]
see above.
